# remote_theme: pmarsceill/just-the-docs
#aux_links:
# "Download Training Scheme of Work":
#     - "https://github.com/silkbusiness/silkbusiness.github.io/raw/main/scheme%20of%20work%20traininng%20contdd.doc"

theme: jekyll-theme-midnight
